name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC token request
  contents: read # Required for checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ECR_ROLE_NAME }} # Your role ARN
          aws-region: ${{ secrets.AWS_REGION }} # Your region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ vars.AWS_ECR_REPO_NAME }} # Your ECR repo name
          IMAGE_TAG: ${{ github.run_id }} # Or use 'latest' or a semantic version
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./frontend/Dockerfile ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
